# Generated by Django 5.1.2 on 2024-12-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('done_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('todo', 'todo'), ('in_process', 'in_process'), ('done', 'done')], max_length=150)),
            ],
        ),
    ]
